# File managed by pluginsync
sudo: false
language: go
go:
- 1.6.3
- 1.7.1
env:
  global:
  - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
  - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
  matrix:
  - TEST_TYPE=small
  - TEST_TYPE=medium
  - TEST_TYPE=build
matrix:
  exclude:
  - go: 1.6.3
    env: TEST_TYPE=build
before_install:
- "[[ -d $SNAP_PLUGIN_SOURCE ]] || mkdir -p $ORG_PATH && ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE"
install:
- cd $SNAP_PLUGIN_SOURCE
- make deps
script:
- make check 2>&1
notifications:
  email: false
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=
before_deploy:
- "./scripts/pre_deploy.sh"
deploy:
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: YyBdd22h/0hl6YtA25GzLsija8Yg8uvF8RjDVwNheqcAEpmroLCq4LMMFo+AubUv+6oGmttLXRPfHk0uP3040Vp44TSTMC/mmRNQl8sxO+h/9UOWTCIFsFFxj0uN6S2oFDutLbqwRlt3pK2kxxGwJwL3PgBqUQ0c4HKNRpqRSSyeCi3+omq9r5C1H+b+XCYPz7kyQHKYRFqAm3441SJV+mInZTQHYz01rMuinN/P/rUEl988w9YxLoaR2keqAY5NVaOh35/Cnih/wVL8wdwcajSv939WblZ6tU/+ZL65d7Zv79zx4JCbeelzCxLBy+ftOaEtsm5F73Q3FGbXNBjmmMC24tDjo6kPVKLQBKRaJ3976LaYYyRw8Y83EytkZ5zntQprB6JtRY2zy0Y5LqUUImGw5A2O403gEZfvuNjROPU38Wd9rwkL0qP1w5dzd8qW2tn4KMARmF04dx8frSc8MXPxrIrEN/NOoH/wBSQFr70iDFrfxpsmjwBZ10HNQUhhLIWRxckpaeFYmxA4cq9OH1XOP/Yvaf9l0HtOouZEdrMOyHTuGr0WiGT7zslosKU0kjSwLStg1K6qyyiIpARNs2mpwNUaReKs8acqIMlPQkJIFfgOPkr819TZ8O6Q4rjsfmglOCWfIIa2UTdSFkwkS2R33vtmdirJWaiK3Pazrus=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-collector-snmp
    branch: master
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: YyBdd22h/0hl6YtA25GzLsija8Yg8uvF8RjDVwNheqcAEpmroLCq4LMMFo+AubUv+6oGmttLXRPfHk0uP3040Vp44TSTMC/mmRNQl8sxO+h/9UOWTCIFsFFxj0uN6S2oFDutLbqwRlt3pK2kxxGwJwL3PgBqUQ0c4HKNRpqRSSyeCi3+omq9r5C1H+b+XCYPz7kyQHKYRFqAm3441SJV+mInZTQHYz01rMuinN/P/rUEl988w9YxLoaR2keqAY5NVaOh35/Cnih/wVL8wdwcajSv939WblZ6tU/+ZL65d7Zv79zx4JCbeelzCxLBy+ftOaEtsm5F73Q3FGbXNBjmmMC24tDjo6kPVKLQBKRaJ3976LaYYyRw8Y83EytkZ5zntQprB6JtRY2zy0Y5LqUUImGw5A2O403gEZfvuNjROPU38Wd9rwkL0qP1w5dzd8qW2tn4KMARmF04dx8frSc8MXPxrIrEN/NOoH/wBSQFr70iDFrfxpsmjwBZ10HNQUhhLIWRxckpaeFYmxA4cq9OH1XOP/Yvaf9l0HtOouZEdrMOyHTuGr0WiGT7zslosKU0kjSwLStg1K6qyyiIpARNs2mpwNUaReKs8acqIMlPQkJIFfgOPkr819TZ8O6Q4rjsfmglOCWfIIa2UTdSFkwkS2R33vtmdirJWaiK3Pazrus=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-collector-snmp
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
- provider: releases
  api_key:
    secure: SE4c+5pw4lt+aij6uN6CRuTxnDc2wjSOiU18ZJj1TmZxhGEBq02MZivacziA6WlmEOhsG4giaR06/MFtZBr4EJH53mn4nbF+K5f6sdG5VIx8ibt3+Vw7A1stNDYBgupWMO0s7kxUSsQUAjCb+u+udEUz6vLjQkFEaASVA+cFXgP9YS3uevIfNOwJ8ipB7cHAA/48+0nS8UfTm0oXD2DbBNiavUSYQbor9Zylfxj/dRcykVANCy2VfTv9j8b86J7BTlnoTMaNGsaUMCYC+gRxapOhh6fj5Dn6XXFRPPpy/zLiUvW3itW8EsyKUgZFOr76nGQ1ptKbmSvfQIw19uNem45ufg2+2Lbwkt+SMinepn8PaVlYtgrxxFpWEQZAkZVrQbudwUdQDlKVTFKvBMtvYJ9frh0AwDwuLRkvyYdOZwPEA3zb6LOhoaeh76cb/EXtdg4HOhJjUmvvdBJ9vmzzh6kKcvKhY/ihKxoBlXOSDvwXIMUVs66jiPR5nDfY2bWYCL5wnve4o+Uj5YJdyAdC5HCsSAuXURCkVSk2JtLP/mVAQZs0P/pnmyurEUZ55c3M2DVWjNE2ksB/KNMLCt7d9uBczaOkLvuvuMNx1xyigwLcuK4/DZAjxgtLi9oqDfVbPRGuEcxvZp06pe1TZJO51ft2gR1lT0R7pNouIdWXVNQ=
  file:
    - release/snap-plugin-collector-snmp_linux_x86_64
  skip_cleanup: true
  on:
    repo: intelsdi-x/snap-plugin-collector-snmp
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
